apiVersion: v1
kind: Service

metadata:
  name: mypython-web-service

spec:
  type: NodePort
  selector:
    app: myweb_label

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007
